---

site_name: MyArchive

database:
  default: mysql
  mysql:
    host: 127.0.0.1
    port: 3306
    db: asagi
    user: asagi
    password: asagi
    charset: utf8mb4
  postgresql:
    host: 127.0.0.1
    port: 5432
    db: asagi
    user: asagi
    password: asagi
    charset: utf8

schema:
  name: asagi

# List of archive boards to show on the front index. 
archives:
  - {shortname: a, name: Anime & Manga}
  - {shortname: aco, name: Adult Cartoons}
  - {shortname: an, name: Animals & Nature}
  - {shortname: c, name: Cute}
  - {shortname: co, name: Comics & Cartoons}
  - {shortname: d, name: Hentai/Alternative}
  - {shortname: fit, name: Fitness}
  - {shortname: his, name: History & Humanities}
  - {shortname: int, name: International}
  - {shortname: k, name: Weapons}
  - {shortname: m, name: Mecha}
  - {shortname: mlp, name: Pony}
  - {shortname: q, name: 4chan Feedback}
  - {shortname: qa, name: Question & Answer}
  - {shortname: r9k, name: ROBOT9001}
  - {shortname: tg, name: Traditional Games}
  - {shortname: trash, name: Off-Topic}
  - {shortname: vr, name: Retro Games}
  - {shortname: wsg, name: Worksafe GIF}

# List of boards to list on the front index page.
# This currently has no function, although it may be used for text 
# boards in the future. 
boards:
  - {shortname: p, name: Photography}

# Template skins, only tested for use on Foolfuuka
skins:
  - {slug: default, name: FoolFuuka - Default}
  - {slug: midnight, name: FoolFuuka - Midnight}
  - {slug: kurimasu, name: FoolFuuka - Christmas}
  - {slug: barentain, name: FoolFuuka - Valentine's Day}
  - {slug: halloween, name: FoolFuuka - Halloween}

default_skin: default

# Template UI options
options:
  post_selector: true
  stats: false
  ghost: false
  search: false

# Image hash format.
# md5 and sha256 are supported.
hash_format: md5

# URL location of images. These files are not currently hosted by ayase,
# although this can be made possible with another StaticFiles mount. 
image_location:
  image: /img/{board_name}/image
  thumb: /img/{board_name}/thumb
# Torako sha256 folder structure
#image_location:
#  image: /img
#  thumb: /img

# OpenAPI scraper info (currently unused).
scraper:
  default: asagi
  asagi:
    name: Asagi
    source: https://github.com/eksopl/asagi
  ena:
    name: Ena
    source: https://github.com/shiimizu/ena

# Show database timings 
debug: false
